config/routes.rb
Rails.application.routes.draw do
  

  root 'customers#index'
  post '/signin', to:'sessions#create'
  delete '/logout', to: 'sessions#destroy'

   resources :customers
   resources :pets
   resources :appointments

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  validates_presence_of :DateOfVisit, :reasonForVisit
  belongs_to :customer
  belongs_to :doctor
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :doctors, through: :appointments 
  has_many :appointments
  has_many :pets , through: :owners
  has_many :owners
end

app/models/docter.rb
class Docter < ActiveRecord::Base
	validates_presence_of :name
	validates_length_of :name, maximum: 35
	validates_length_of :zip, maximum: 5
	validates_length_of :yip, within: 1..100
	has_many :customers, through: :appointments
	has_many :appointments
end

app/models/owner.rb
class Owner < ActiveRecord::Base
	belongs_to :pet
  belongs_to :customer
end

app/models/pet.rb
class Pet < ActiveRecord::Base
	validates_presence_of :name, :breed, :age, :weight, :dateOfLastVisit
	has_many :customers , through: :owners
	has_many :owners
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
  	
  end
  def new
  	@appointment = Appointment.new
  end

  def create
  	@appointment = Appointment.new(appointment_params)
     if @appointment.save
       flash[:notice] = "You have created appointment successfully."
       redirect_to appointment_path @appointment
     else
       flash[:alert] = "There was a problem saving your
       appointment."
       redirect_to new_appointment_path
     end
  end

  def show
  	@appointment = Appointment.find(params[:id])
  	
  end

  def delete
    @appointment = Appointment.find(params[:id])
    @appointment.delete
  end

  private
  def appointment_params
    params.require(:appointment).permit(:reasonForVisit, :DateOfVisit)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
  	
  end
  def new
  	@customer = Customer.new
  end

  def create
  	@customer = Customer.new(customer_params)
     if @customer.save
       flash[:notice] = "You have registered successfully."
       redirect_to customer_path @customer
     else
       flash[:alert] = "There was a problem saving your
       account."
       redirect_to new_customer_path
     end
  end

  def show
  	@customer = Customer.find(params[:id])
  	@pets = @customer.pets
  end

  def delete
    @customer = Customer.find(params[:id])
    @customer.delete
  end


  private
  def customer_params
    params.require(:customer).permit(:name, :email, :password)
  end
end

app/controllers/docters_controller.rb
class DoctersController < ApplicationController
  def index
  	
  end
  def new
  	@docter = Docter.new
  end

  def create
  	@docter = Docter.new(docter_params)
     if @docter.save
       flash[:notice] = "You have registered successfully."
       redirect_to docter_path @docter
     else
       flash[:alert] = "There was a problem saving your
       account."
       redirect_to new_docter_path
     end
  end

  def show
  	@docter = Docter.find(params[:id])
  	@customers = @docter.customers
  end

  def delete
    @docter = Docter.find(params[:id])
    @docter.delete
  end


  private
  def docter_params
    params.require(:docter).permit(:name, :address, :city, :state, :zip, :school, :yip)
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    
  end
  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pets_params)
     if @pet.save
       flash[:notice] = "You have created a new pet successfully."
       redirect_to pet_path @pet
     else
       flash[:alert] = "There was a problem saving your
       pet."
       redirect_to new_pet_path
     end
  end

  def show
    @pet = Pet.find(params[:id])
    
  end

  def delete
    @pet = Pet.find(params[:id])
    @pet.delete
  end


  private
  def pets_params
    params.require(:pet).permit(:name, :owner ,:breed, :age , :weight , 
      :dateOfLastVisit)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		
			@customer=Customer.find_by(email: params[:email])
			
			if @customer
	            if @customer.password == params[:password]
				flash[:notice]="Successfully signed in!"
				session[:user_id]=@customer.id
				redirect_to customer_path(@customer.id)
			 else
			    flash[:alert]="Customer does not exist. Please sign up."
			    redirect_to customers_path
		    end
		end
	end

	 
	def destroy
		session[:user_id]=nil
		flash[:notice]="Logged out..."
		redirect_to root_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/docters_helper.rb
module DoctersHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/appointments/index.html.erb
<h1>Appointments#index</h1>
<p>Find me in app/views/appointments/index.html.erb</p>

app/views/appointments/new.html.erb
<%= form_for @appointment do |f| %>
 <%= f.label :reasonForVisit %>
 <%= f.text_field :reasonForVisit %>
 <%= f.label :DateOfVisit%>
 <%= f.datetime_field :DateOfVisit %>
 <%=f.submit :Register %>
  <% end %>

app/views/customers/index.html.erb
<h1>Welcome to Vet Clinic...</h1>
<%= link_to "New Patient? Signup", new_customer_path %>
<div class="form_class"><%= form_tag(signin_path, method: :post) do %>
        <%= label_tag :name %>
	    <%= text_field_tag :name %>
	    <%= label_tag :email %>
	    <%= email_field_tag :email %>
	    <%= label_tag :password %>
        <%= password_field_tag :password %>
	    <%= submit_tag "login" %>
	  <%end%>
</div>

app/views/customers/new.html.erb
<%= form_for @customer do |f| %>
 <%= f.label :name %>
 <%= f.text_field :name %>
 <%= f.label :email%>
 <%= f.email_field :email %>
 <%= f.label :password %>
 <%= f.password_field :password %>
 <%=f.submit :Register %>
  <% end %>

  

app/views/customers/show.html.erb
<%= "Hello #{@customer.name}"%>
<%= link_to 'Add pet' ,:controller => 'pets', :action => 'new', :customer_id => @customer.id %>
<%= link_to 'Make an Appointment' ,:controller => 'appointments', :action => 'new', :customer_id => @customer.id %>
<div id="board">   
   <%= content_tag :div do %>
	<div class="header">
	
	
	</div>
	
	<% end %>
</div>

app/views/docters/index.html.erb
<h1>Welcome to Vet Clinic...</h1>
<%= form_for @customer do |f| %>
 <%= f.label :name, 'Name' %>
 <%= f.text_feild :name %>
 %= f.label :email, 'Email' %>
 <%= f.email_feild :email %>
 %= f.label :password, 'Password' %>
 <%= f.password_feild :password %>
 <%=f.submit :Signin %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyVetOffice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
 <%= flash[:notice] if flash[:notice] %>
 <%= flash[:alert] if flash[:alert] %>

</body>
</html>

app/views/pets/index.html.erb
<h1>Pets#index</h1>
<p>Find me in app/views/pets/index.html.erb</p>

app/views/pets/new.html.erb
<%= form_for @pet , do |f| %>
 <%= f.label :name %>
 <%= f.text_field :name %>
 <%= f.label :type%>
 <%= f.text_field :type %>
 <%= f.label :breed%>
 <%= f.text_field :breed %>
 <%= f.label :age %>
 <%= f.number_field :age %>
 <%= f.label :weight %>
 <%= f.number_field :weight %>
 <%= f.label :dateOfLastVisit%>
 <%= f.datetime_field :dateOfLastVisit %>
 <%= f.hidden_field :customer_id %>
 <%=f.submit :Add %>
  <% end %>

  

app/views/pets/show.html.erb
<%= @pet %>